### ISSUE TITLE
有没有办法从其他网页打开 mess-reader

### ISSUE THREAD

**Issue by yenche123** [ppz-pro/mess-reader#7]
首先，先感谢作者这个作品！真的很棒！
我的网页里有一些 `epub` 格式的文件，我想帮助用户无缝的预览，在想有没有办法靠传参之类的办法或其他方式，让用户点击后直接到 mess-reader 上阅读。

**Comment by daGaiGuanYu** [comment]
不好意思，这几天感冒发烧没看 github  

我有个打算做的功能是：
+ 把 epub 电子书的下载链接放在 url 里
+ 网页程序读取 url 里的链接，然后打开电子书

如果你们的 epub 是可以公开下载（比如不需要 token）的，这个功能应该可以满足你的需求

如果不能的话，可以在下面再详细描述一下

**Comment by yenche123** [comment]
> 不好意思，这几天感冒发烧没看 github
> 
> 我有个打算做的功能是：
> 
> * 把 epub 电子书的下载链接放在 url 里
> * 网页程序读取 url 里的链接，然后打开电子书
> 
> 如果你们的 epub 是可以公开下载（比如不需要 token）的，这个功能应该可以满足你的需求
> 
> 如果不能的话，可以在下面再详细描述一下

嗯嗯，我目前也只能想到这个方案。
btw, 祝身体健康，早日痊愈！

**Comment by yenche123** [comment]
@daGaiGuanYu 我发现 web share api 可以分享 Blob 文件
![image](https://github.com/ppz-pro/mess-reader/assets/28533125/23cc4437-a4cc-4966-8ff8-82c9890cfee7)
https://web.dev/patterns/files/share-files/

但奇怪的是，我用 w3c 的 Web Share Test 这个 [Demo](https://w3c.github.io/web-share/demos/share-files.html) 试着分享 `.epub` 的文件，却出现 `NotAllowedError: Permission denied` 的错误，然而其他 `pdf` / `mp4` / `jpg` 的文件却都没问题。

看起来这个 API 对文件格式有一定限制。

**Comment by yenche123** [comment]
这是 web share api 关于接收外部文件的示例: https://web.dev/patterns/files/receive-shared-files/
在 `manifest.json` 下定义 `share_target`，跟 `file_handlers` 稍有不同

**Comment by daGaiGuanYu** [comment]
我大概看了下 https://web.dev/patterns/files/share-files/  
感觉应该是一个**纯前端**的“分享 api”  
它应该不会提供文件下载功能，[那个 Demo](https://w3c.github.io/web-share/demos/share-files.html) 生成的链接是你填入的链接，没有上传到什么服务器然后共别人下载

我不太清楚你的需求，但是如果你需要一个“分享”页面，可以不必使用浏览器内置的 api  
我瞎猜的哈：你可能不需要一个分享页面

你可以提供一个链接比如 `https://ppz-pro.github.io/mess-reader/?download=文件下载链接`  
然后：
1. 用户点了这个链接
2. 浏览器会打开 `mess reader`
3. `mess reader` 读取浏览器地址栏的 url 里的参数
4. 自动下载 epub、打开 epub

我正在做 3 和 4

**Comment by yenche123** [comment]
嗯我的需求是纯前端的。
因为是本地文件。

云文件，`mess-reader` 侧还需要下载；纯前端则无需下载，速度更快、体验更好，跨 Web App 文件互通。

**Comment by daGaiGuanYu** [comment]
e，，，纯前端，，真的能传输文件吗，文件存哪呢

**Comment by daGaiGuanYu** [comment]
终于有时间做了 https://ppz-pro.github.io/mess-reader/?t=https%3A%2F%2Fs3.amazonaws.com%2Fmoby-dick%2Fmoby-dick.epub

把电子书下载链接作为参数（需要 encode），[简要介绍](https://github.com/ppz-pro/mess-reader/blob/main/doc/share.md)
