### ISSUE TITLE
怎么使用呢？

### ISSUE THREAD

**Issue by zhl111** [ppz-pro/mess-reader#9]
请教您，对于不懂编程的人来说不知如何上手，如何才能使用？安装怎么装？我都不太懂，还望指教

这个在网页端看英文书非常地好，可以使用插件解决翻译问题，但又不会用，十分地着急

**Comment by daGaiGuanYu** [comment]
不好意思，消息提醒好像不小心点掉了，刚看到

如果你使用 chrome 或 edge 浏览器的话，在地址栏的右侧，应该会有一个四四方方的图标，点那个就可以安装了

![222](https://github.com/ppz-pro/mess-reader/assets/27003009/b7d3f146-3547-4070-a307-3c497f424c98)

如果有其他问题，欢迎进群聊天，二维码七天有效
![PPz总群](https://github.com/ppz-pro/mess-reader/assets/27003009/fe0d05a7-8ace-4d8f-8329-aa86a80ad87d)
